#! /usr/bin/env python

import argparse
import bz2
import pickle

from mmlkg.data import dataset


_MODALITIES = ["textual", "numerical", "temporal", "visual", "spatial"]


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", help="Directory with CSV files "
                        + "(generated by `generateInput.py`)",
                        required=True)
    parser.add_argument("-m", "--modalities", nargs='*',
                        help="Which modalities to include",
                        choices=[m.lower() for m in _MODALITIES],
                        default=_MODALITIES)
    parser.add_argument("-o", "--output", help="Output directory",
                        default=None)
    flags = parser.parse_args()

    out_dir = flags.input if flags.output is None else flags.output
    out_dir = out_dir + '/' if not out_dir.endswith('/') else out_dir

    data = dataset.generate_pickled(flags)
    with bz2.BZ2File(out_dir + 'dataset.pbz2', 'wb') as f:
        pickle.dump(data, f)
